name: 'openpilot env setup, with retry on failure'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 30
  use_native_setup:
    description: 'Use native optimized setup instead of Docker (default: true for faster builds)'
    required: false
    default: 'true'

outputs:
  duration:
    description: 'Duration of the setup process in seconds'
    value: ${{ steps.get_duration.outputs.duration }}

runs:
  using: "composite"
  steps:
    - id: start_time
      shell: bash
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
    # Native setup attempts
    - id: setup1-native
      if: inputs.use_native_setup == 'true'
      uses: ./.github/workflows/setup-native-optimized
      continue-on-error: true
      with:
        is_retried: true
    - id: setup1-docker
      if: inputs.use_native_setup != 'true'
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        is_retried: true
    
    # Sleep before retry if first attempt failed
    - if: (steps.setup1-native.outcome == 'failure' && inputs.use_native_setup == 'true') || (steps.setup1-docker.outcome == 'failure' && inputs.use_native_setup != 'true')
      shell: bash
      run: sleep ${{ inputs.sleep_time }}
    
    # Second attempt
    - id: setup2-native
      if: inputs.use_native_setup == 'true' && steps.setup1-native.outcome == 'failure'
      uses: ./.github/workflows/setup-native-optimized
      continue-on-error: true
      with:
        is_retried: true
    - id: setup2-docker
      if: inputs.use_native_setup != 'true' && steps.setup1-docker.outcome == 'failure'
      uses: ./.github/workflows/setup
      continue-on-error: true
      with:
        is_retried: true
        
    # Sleep before final retry if second attempt failed
    - if: (steps.setup2-native.outcome == 'failure' && inputs.use_native_setup == 'true') || (steps.setup2-docker.outcome == 'failure' && inputs.use_native_setup != 'true')
      shell: bash
      run: sleep ${{ inputs.sleep_time }}
      
    # Final attempt
    - id: setup3-native
      if: inputs.use_native_setup == 'true' && steps.setup2-native.outcome == 'failure'
      uses: ./.github/workflows/setup-native-optimized
      with:
        is_retried: true
    - id: setup3-docker
      if: inputs.use_native_setup != 'true' && steps.setup2-docker.outcome == 'failure'
      uses: ./.github/workflows/setup
      with:
        is_retried: true
    - id: get_duration
      shell: bash
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "Total duration: $DURATION seconds"
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
